# See ./config.example.yml for an example config file
# Do not leave any fields blank.

personal:
  name: 
  bio: 
  company: 
  location: 

contact:
  email: 
  phone: 

socials: 
  - platform: github
    user: 
  - platform: linkedin
    user: 
  - platform: facebook
    user: 
  - platform: instagram
    user: 
  - platform: twitter
    user: 

projects:
  - name: 
    description: 
    link: 
    source: 
    languages: 
    photo: 

skills:
  - language: 
    level: 
    