personal:
  name: Ivan Chen
  bio: Software Engineer
  company: StuyPulse
  location: New York, NY

contact:
  email: me@ivanchen.dev
  phone: 9177039398

socials: 
  github_username: anivanchen
  linkedin_username: anivanchen
  facebook_username: anivanchen 
  instagram_username: anivanchen
  twitter_username: _anivanchen

projects:
  name: 
    description: 
    link: 
    source: 
    languages: 
    photo: 

skills:
  language: Python
  language: TypeScript
  language: JavaScript
  language: Java
  language: HTML
  language: CSS